ENH Improved readability of sake's which check
The previous implementation used '&&' piping
wich is handled differently in PHP and Bash code
and therefore, may be confusing to a PHP developer.
I refactored the function to use a traditional if statement.

diff --git a/sake b/sake
--- a/sake
+++ b/sake
@@ -9,7 +9,10 @@ Executes a SilverStripe command"
 	exit 1
 fi
 
-command -v which >/dev/null 2>&1 || { echo >&2 "Error: sake requires the 'which' command to operate."; exit 1; }
+if ! command -v which >/dev/null 2>&1; then
+  echo "Error: sake requires the 'which' command to operate." >&2
+  exit 1
+fi
 
 # find the silverstripe installation, looking first at sake
 # bin location, but falling back to current directory
